# -*- coding: utf-8 -*-
"""Python Stats.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g6KEr4iz55Bn75hz22d293NCA6_iECSz

### One-sample T-test with Python
"""

import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt
import math
np.random.seed(6)
population_ages1=stats.poisson.rvs(loc=18,mu=35,size=150000)
population_ages2=stats.poisson.rvs(loc=18,mu=10,size=100000)
population_ages=np.concatenate((population_ages1,population_ages2))
gujarat_ages1=stats.poisson.rvs(loc=18,mu=30,size=30)
gujarat_ages2=stats.poisson.rvs(loc=18,mu=10,size=20)
gujarat_ages=np.concatenate((gujarat_ages1,gujarat_ages2))
population_ages.mean()

gujarat_ages.mean()

stats.ttest_1samp(a=gujarat_ages,popmean=population_ages.mean())

"""### Two-sample T-test With Python"""

np.random.seed(12)
maharashtra_ages1=stats.poisson.rvs(loc=18,mu=33,size=30)
maharashtra_ages2=stats.poisson.rvs(loc=18,mu=13,size=20)
maharashtra_ages=np.concatenate((maharashtra_ages1,maharashtra_ages2))
maharashtra_ages.mean()

stats.ttest_ind(a=gujarat_ages,b=maharashtra_ages,equal_var=False)

"""### Paired T-test With Python"""

np.random.seed(11)
before=stats.norm.rvs(scale=30,loc=250,size=100)
after=before+stats.norm.rvs(scale=5,loc=-1.25,size=100)
weight_df=pd.DataFrame({"weight_before":before,
                         "weight_after":after,
                         "weight_change":after-before})
weight_df.describe()

stats.ttest_rel(a=before,b=after)

"""### KS Test in Python Stats"""

stats.kstest(x,'t',(10,))

stats.kstest(x,'norm')

stats.ks_2samp(gujarat_ages,maharashtra_ages)

"""### Correlation in Python"""

import pandas as pd
import numpy as np
df=pd.read_csv("C:/Users/Khushbu Upadhyay/Desktop/Supermarket.csv")

df.corr()

df.cov()

"""### Plotting Correlation in Python"""

import seaborn as sn
df1=sn.load_dataset('iris')
sn.pairplot(df,kind='scatter')

